name: Build ZEIN EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libs
        run: pip install pyinstaller psutil requests cryptography

      - name: Build EXE
        run: pyinstaller --onefile --name "ZEIN_Agent" zein_agent.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.0
          files: dist/ZEIN_Agent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
