name: Build ZEIN EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libs
        run: pip install pyinstaller psutil requests cryptography

      - name: Build EXE
        run: pyinstaller --onefile --name "ZEIN_Agent" zein_agent.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.0
          name: "ZEIN Agent v2.0"
          files: dist/ZEIN_Agent.exe
          token: ${{ secrets.GITHUB_TOKEN }}
